const quiz =
    [
        {"Number":1,
            "Question" : "In 2003 England beat Australia in a monumental sporting event. The match with 16 seconds left of overtime on the clock, resulting in the first ever win for England in this event. What sport am I referring to?",
              "Correct_Answer": "Rugby Union",
              "Incorrect_Answers": ["Rugby League", "Soccer", "Cricket"],
              "Additional_Info": "",
               "Category":"Sports"},

        {"Number":2,
            "Question":"Australia has multiple sports that are played professionally that could be considered 'Football', how many are there?",
            "Correct_Answer":"4",
            "Incorrect_Answers":["2","3","5"],
            "Additional_Info":"Rugby League, Rugby Union, Soccer and Aussie Football(AFL)",
            "Category":"Sports"},
        {"Number":3,
            "Question":"Who was the most recent Australian male to win Wimbledon?",
            "Correct_Answer":"Leighton Hewitt",
            "Incorrect_Answers":["Mark Philippoussis","Nick Kyrgios","Bernard Tomic"],
            "Additional_Info":"",
            "Category":"Sports"},
        {"Number":4,
            "Question":"Don Bradman is one of Australia's most famous Cricketers, what was his batting average?",
            "Correct_Answer":"99.94",
            "Incorrect_Answers":["49.17","78.85","82.19"],
            "Additional_Info":"",
            "Category":"Sports"},
        {"Number":5,
            "Question":"What sporting event in Australia is known as the 'Race that stops the nation'?",
            "Correct_Answer":"Melbourne Cup",
            "Incorrect_Answers":["Australian Grand Prix","Stawell Gift","Bathurst 1000"],
            "Additional_Info":"",
            "Category":"Sports"},
        {"Number":6,
            "Question":"Which Australian sports star was Liz Hurley caught snogging in 2010 at outside London restaurant Sake No Hana, who she would later become engaged to?",
            "Correct_Answer":"Shane Warne",
            "Incorrect_Answers":["Daniel Riccardo","Justin Thurston","David Warner"],
            "Additional_Info":"",
            "Category":"Sports"},
        {"Number":7,
            "Question":"Russel Crowe, famous actor and phone throwing world champion grew up in Sydney but he isn't actually Australian. What country was he born in?",
            "Correct_Answer":"New Zealand",
            "Incorrect_Answers":["Tonga", "Papua New Guinea","Solomon Islands"],
            "Additional_Info":"",
            "Category":"Famous Australians"},
        {"Number":8,
        "Question":"What is the name of the Australian actor who plays Thor in the Marvel universe?",
            "Correct_Answer":"Chris Hemsworth",
            "Incorrect_Answers":["Liam Hemsworth","Hugh Jackman","Eric Bana"],
            "Additional_Info":"",
            "Category":"Famous Australians"},
        {"Number":9,
            "Question":"The two brothers who founded one of Australia's most famous bands AC/DC, were not actually born in Australian. Which country from the UK are they from?",
            "Correct_Answer":"Scotland",
            "Incorrect_Answers":["England","Wales","Northern Island"],
            "Additional_Info":"",
            "Category":"Famous Australians"},
        {"Number":10,
            "Question":"Which Australian Actor who also is a British citizen, is known for his stage performances including 'Les Miserables', 'Greatest showman of all time' and 'Boy from Oz'?",
            "Correct_Answer":"Hugh Jackman",
            "Incorrect_Answers":["Liam Hemsworth","David Atkins","Russel Crow"],
            "Additional_Info":"",
            "Category":"Famous Australians"},
        {"Number":11,
            "Question":"How many No 1 singles has Kyle Monogue had in the UK?",
            "Correct_Answer":"7",
            "Incorrect_Answers":["3","10","16"],
            "Additional_Info":"",
            "Category":"Famous Australians"},
        {"Number":12,
            "Question":"Which Australian SuperModel has the nickname 'The Body'?",
            "Correct_Answer":"Elle Mcpherson",
            "Incorrect_Answers":["Miranda Kerr","Robyn Lawler","Jessica Hart"],
            "Additional_Info":"",
            "Category":"Famous Australians"},
        {"Number":13,
            "Question":"Neighbours is filmed on a real stretch of road in Australia. What is the name of it according to Google Maps?",
        "Correct_Answer":"Pin Oak Court",
        "Incorrect_Answers":["Ramsay Street","White Ash Court","Weeden Drive"],
        "Additional_Info":"",
        "Category":"Neighbours"},
    {"Number":14,
        "Question":"Only one episode of Neighbours has been filmed outside of Australia. Which city was it filmed in?",
        "Correct_Answer":"London",
        "Incorrect_Answers":["Brighton","Bristol","Manchester"],
        "Additional_Info":"",
        "Category":"Neighbours"},
    {"Number":15,
        "Question":"Who is the only original character left currently in Neighbours?",
        "Correct_Answer":"Paul Robinson",
        "Incorrect_Answers":["Susan Kennedy","Karl Kennedy","Lou Carpenter"],
        "Additional_Info":"",
        "Category":"Neighbours"},
    {"Number":16,
        "Question":"Which Little Britain character/characters has/have appeared as a cameo part on Neighbours, which aired in the UK in September 2007?",
        "Correct_Answer":"Lou and Andy",
        "Incorrect_Answers":["Daffyd Thomas","Bubbles Devere","Kenny Craig"],
        "Additional_Info":"",
        "Category":"Neighbours"},
    {"Number":17,
        "Question":"Approximately how many people in the UK watched Scott and Charlene's wedding episode?",
        "Correct_Answer":"20 Million",
        "Incorrect_Answers":["10 Million","15 million","25 Million"],
        "Additional_Info":"19.6 Million",
        "Category":"Neighbours"},
    {"Number":18,
        "Question":"What is Toadie's real name in the show?",
        "Correct_Answer":"Jarrod Rebecchi",
        "Incorrect_Answers":["Paul Robinson","Harrold Bishop","Jay Rebecchi"],
        "Additional_Info":"",
        "Category":"Neighbours"},
    {"Number":19,
        "Question":"The UK's total land mass is 242,495 km2. How many times larger is Australia than the UK?",
        "Correct_Answer":"32",
        "Incorrect_Answers":["12","26","41"],
        "Additional_Info":"Aus land mass: 7,692,000 km², UK land mass: 242,495 km²",
        "Category":"Geography"},
    {"Number":20,
        "Question":"What is the capital city of Australia?",
        "Correct_Answer":"Canberra",
        "Incorrect_Answers":["Sydney","Melbourne","Perth"],
        "Additional_Info":"",
        "Category":"Geography"},
    {"Number":21,
        "Question":"What is the biggest state in Australia, by land mass?",
        "Correct_Answer":"Western Australia",
        "Incorrect_Answers":["Queensland","New South Wales",""],
        "Additional_Info":"",
        "Category":"Geography"},
    {"Number":22,
        "Question":"How many hours difference is the time zone between Perth and Brisbane, non daylight savings?",
        "Correct_Answer":"2 Hours",
        "Incorrect_Answers":["1 Hour","3 Hours","4 Hours"],
        "Additional_Info":"",
        "Category":"Geography"},
    {"Number":23,
        "Question":"How long would it take you to fly direct from Brisbane on the east coast to Perth on the west approx?",
        "Correct_Answer":"5 Hours",
        "Incorrect_Answers":["3 Hours","4 Hours","6 Hours"],
        "Additional_Info":"",
        "Category":"Geography"},
    {"Number":24,
        "Question":"What famous beach town is the most easterly point of mainland Australia?",
        "Correct_Answer":"Byron Bay",
        "Incorrect_Answers":["Evans Head","Summer Bay","Sydney"],
        "Additional_Info":"",
        "Category":"Geography"},
    {"Number":25,
        "Question":"The 2nd of January 1960, in Oodnadatta was the hottest day ever recorded in Australian recorded history. How hot was it?",
        "Correct_Answer":"53 Degrees Celsius",
        "Incorrect_Answers":["43 Degrees Celsius","50 Degrees Celsius","47 Degrees Celsius"],
        "Additional_Info":"",
        "Category":"General Knowledge"},
    {"Number":26,
        "Question":"What is the square-shaped sponge cake that is coated in a layer of chocolate icing and desiccated coconut and often described as the 'National Cake of Australia'?",
        "Correct_Answer":"Lamington",
        "Incorrect_Answers":['Sponge Cake',"Cup Cake","Fairy Bread"],
        "Additional_Info":"",
        "Category":"General Knowledge"},
    {"Number":27,
        "Question":"What is the name of the famous Australian spread, that so polarises people across the world?",
        "Correct_Answer":"Vegemite",
        "Incorrect_Answers":["Marmite","Promite","Strawberry Jam"],
        "Additional_Info":"",
        "Category":"General Knowledge"},
    {"Number":28,
        "Question":"The pub quiz is a stable in British pub life, what is a pub quiz called in Australia?",
        "Correct_Answer":"Trivia",
        "Incorrect_Answers":["Pub Quiz","The Quiz","Fiddle-Faddle"],
        "Additional_Info":"",
        "Category":"General Knowledge"},
    {"Number":29,
        "Question":"What is the Australian nickname for brief style swimming trunks?",
        "Correct_Answer":"Budgie Smugglers",
        "Incorrect_Answers":["Fish Frighteners","Banana Hammock","Cucumber Concealer"],
        "Additional_Info":"",
        "Category":"General Knowledge"},
    {"Number":30,
        "Question":"What beautifully Australian activity did Australia’s Ex Prime Minister, Bob Hawke hold the world record in during his university years at Oxford?",
        "Correct_Answer":"Drinking a Yard of beer",
        "Incorrect_Answers":["Fastest Final Exam Time","Lowest GPA","Highest Debating Score"],
        "Additional_Info":"He drank a yard of Beer in 11.2 seconds (2 Imperial Pints)",
        "Category":"General Knowledge"}
    ]

module.exports = {quiz}